// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DryRunClaudeCodeExport(arg1) {
  return window['go']['main']['App']['DryRunClaudeCodeExport'](arg1);
}

export function ExportClaudeCodeSessions(arg1) {
  return window['go']['main']['App']['ExportClaudeCodeSessions'](arg1);
}

export function GetArchiveStorageInfo() {
  return window['go']['main']['App']['GetArchiveStorageInfo']();
}

export function ListClaudeCodeExportPaths() {
  return window['go']['main']['App']['ListClaudeCodeExportPaths']();
}

export function RestoreClaudeCodeSessions(arg1) {
  return window['go']['main']['App']['RestoreClaudeCodeSessions'](arg1);
}

export function ScanClaudeCodeSessions() {
  return window['go']['main']['App']['ScanClaudeCodeSessions']();
}
