// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ccarchive} from '../models';

export function DryRunClaudeCodeExport(arg1:ccarchive.ExportRequest):Promise<ccarchive.DryRunResult>;

export function ExportClaudeCodeSessions(arg1:ccarchive.ExportRequest):Promise<ccarchive.ExportResult>;

export function GetArchiveStorageInfo():Promise<ccarchive.StorageInfo>;

export function ListClaudeCodeExportPaths():Promise<Array<string>>;

export function RestoreClaudeCodeSessions(arg1:ccarchive.RestoreRequest):Promise<ccarchive.RestoreResult>;

export function ScanClaudeCodeSessions():Promise<ccarchive.ScanResult>;
